// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApKiG6ASEGFkR9_3UcKPIZx8KqLGtCETg',
    appId: '1:432225577493:web:e3438716436a0edffdbc1c',
    messagingSenderId: '432225577493',
    projectId: 'news-app-a26',
    authDomain: 'news-app-a26.firebaseapp.com',
    storageBucket: 'news-app-a26.firebasestorage.app',
    measurementId: 'G-ZD16TP69WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMbR9JjVFR7rKb3Mg0M4BEnEfxDFmIQFY',
    appId: '1:432225577493:android:589153eca73a4d4ffdbc1c',
    messagingSenderId: '432225577493',
    projectId: 'news-app-a26',
    storageBucket: 'news-app-a26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzymO33SfKI3yI44B30zWJytzyILZZV-I',
    appId: '1:432225577493:ios:5e6df84033cafad4fdbc1c',
    messagingSenderId: '432225577493',
    projectId: 'news-app-a26',
    storageBucket: 'news-app-a26.firebasestorage.app',
    iosBundleId: 'com.example.newsAppFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzymO33SfKI3yI44B30zWJytzyILZZV-I',
    appId: '1:432225577493:ios:5e6df84033cafad4fdbc1c',
    messagingSenderId: '432225577493',
    projectId: 'news-app-a26',
    storageBucket: 'news-app-a26.firebasestorage.app',
    iosBundleId: 'com.example.newsAppFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApKiG6ASEGFkR9_3UcKPIZx8KqLGtCETg',
    appId: '1:432225577493:web:00dcf451cfd77054fdbc1c',
    messagingSenderId: '432225577493',
    projectId: 'news-app-a26',
    authDomain: 'news-app-a26.firebaseapp.com',
    storageBucket: 'news-app-a26.firebasestorage.app',
    measurementId: 'G-DXB9YXN7RS',
  );
}
