import 'package:flutter/material.dart';

class NewsCategory {
  final String id;
  final String title;
  final IconData icon;

  const NewsCategory({
    required this.id,
    required this.title,
    required this.icon,
  });
}

class AppCategories {
  // This now perfectly mirrors the 5 categories generated by the Python backend!
  static const List<NewsCategory> allCategories = [
    NewsCategory(id: 'top_news', title: 'Top News', icon: Icons.newspaper),
    NewsCategory(
      id: 'world_politics',
      title: 'World Politics',
      icon: Icons.public,
    ),
    NewsCategory(id: 'sports', title: 'Sports', icon: Icons.sports_soccer),
    NewsCategory(id: 'business', title: 'Business', icon: Icons.trending_up),
    NewsCategory(id: 'weather', title: 'Weather', icon: Icons.cloud_outlined),
  ];
}
